repository:
  # A comma-separated list of topics to set on the repository
  topics: cucumber, community, bdd

branches:
  - name: release/*
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: false
      required_linear_history: false
      restrictions:
        teams:
          - @cucumber/release
